### ISSUE TITLE
missing sections in the printed version

### ISSUE THREAD

**Issue by losataschu** [pdeitel/JavaHowToProgram11e_EarlyObjects#1]
Hello,
I'm currently learning the basics on design patterns and to get an overview I looked in the online appendix N "Design Patterns".
There are references to the book that I cannot find in mine (Java How To Program, 11th edition, ISBN 978-0-13-474335-6) e.g. in the description of Adapter pattern it is mentioned section 12.15 or Strategy pattern mentions section 12.18, and in my book chapter 12 has only seven sections. I looked for the book's table of contents available online and couldn't find a longer chapter 12 (this also happens with other chapters). Is it any possibility to find the references included in the appendices in other sections or to obtain the missing parts? That would be very helpful.
Kind Regards,
Lorenzo TS

P.S.: here's a link to the table of contents provided by Pearson's website https://media.pearsoncmg.com/ph/esm/deitel/java_htplo_11/cw/content/sample-chapters/jhtpTOC.pdf

**Comment by pdeitel** [comment]
Hi, That appendix is pretty out of date and if possible, I’d try to get a more recent publication on design patterns.

For the last edition of our Java book, all we did was post the old version of it, which might have been from either the 9th or 10th edition of the book.

Those references were to the Swing GUI chapter, which is an online chapter in the last edition. I believe it was Chapter 26.

Best,
Paul

From: Lorenzo TS ***@***.***>
Date: Thursday, January 12, 2023 at 5:26 AM
To: pdeitel/JavaHowToProgram11e_EarlyObjects ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pdeitel/JavaHowToProgram11e_EarlyObjects] missing sections in the printed version (Issue #1)

Hello,
I'm currently learning the basics on design patterns and to get an overview I looked in the online appendix N "Design Patterns".
There are references to the book that I cannot find in mine (Java How To Program, 11th edition, ISBN 978-0-13-474335-6) e.g. in the description of Adapter pattern it is mentioned section 12.15 or Strategy pattern mentions section 12.18, and in my book chapter 12 has only seven sections. I looked for the book's table of contents available online and couldn't find a longer chapter 12 (this also happens with other chapters). Is it any possibility to find the references included in the appendices in other sections or to obtain the missing parts? That would be very helpful.
Kind Regards,
Lorenzo TS

P.S.: here's a link to the table of contents provided by Pearson's website https://media.pearsoncmg.com/ph/esm/deitel/java_htplo_11/cw/content/sample-chapters/jhtpTOC.pdf
